name: 'Regen Builds'

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ regen-builds ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  regen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout downloads-www
        uses: actions/checkout@v5

      - name: Retrieve the builds
        uses: tidev/titanium-builds-regen-action@v6
        with:
          output-dir: 'public/registry'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        id: committed
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: Repository Dispatch
        if: steps.committed.outputs.changes_detected == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: deploy
          token: ${{ secrets.REGEN_BUILDS_DOCS_GITHUB_TOKEN }}
